### ISSUE TITLE
Going down hill breaks chain

### ISSUE THREAD

**Issue by NealSavage** [CammiesCorner/Cammies-Minecart-Tweaks#18]
Going down this hill then straight again is breaking the chain linking my carts together 

![image](https://user-images.githubusercontent.com/4138801/162551414-18d09690-ff9f-4c02-a1d2-46202534e64a.png)

**Comment by CammiePone** [comment]
That's because they're getting too far apart. Not a bug, technically fixed in dev anyways for lag compensation reasons, please I appreciate that you're trying to be help weed out bugs but please spread the reports apart ;-;

Like, 2 a day tops would be ideal since then it still gets the info across but my sanity can't take it dude ;-;

**Comment by NealSavage** [comment]
Haha, okay, okay, I'll wait for the next release and its fixes to test more. Honestly not trying to drive you insane lmao
