### ISSUE TITLE
Chains dissapear when minecarts go through nether portal (mb end portal too but i didn't tested that)

### ISSUE THREAD

**Issue by SimplyTolex** [CammiesCorner/Cammies-Minecart-Tweaks#32]
This makes impossible to just send minecart train through dimensions, as the player will need to:
- get off the minecart (since minecart with a player doesn't teleport at all for some reason)
- go through the portal
- _find a new minecart with furnace_ (since the old one happily left without you and your cargo)
- _reconnect everything with chains_ (that you also need to find because the old ones vanished and not dropped like they usually do)
- and only then continue

It's not really a big problem, but it's still kinda bothers me

**Comment by CammiePone** [comment]
the way Minecraft moves entities through portals kinda necessitates it breaks the chains. it basically kills the entity and spawns a new one with the same data

however, because the parent and child dont exist at the exact same time on one side of the portal, it snaps so as to prevent crashing the game

**Comment by CammiePone** [comment]
it might be something I can find a hacky solution for, but the question is can I be assed to
